### ISSUE TITLE
Stuck on red screen.

### ISSUE THREAD

**Issue by frap129** [jirutka/swaylock-effects#3]
After this package was brought inline with upstream, it no longer works for me. The screen turns completely red except for the cursor, which is still visible and usable. Typing does not bring up the indicator or allow me to unlock, I have to reboot using the power button to get back in. It doesn't seem to be related to any config option, as simply running swaylock from a terminal causes the issue. This is happening on both my personl and work systems, both running Arch Linux, one with intel+nvida graphics and one with AMD, so it doesn't seem to be related to graphics drivers. I have tried with both sway (and wlroots) stable and sway-git (wlroots-git), issue occurs in both scenarios.

Output of `swaylock -d 2> log.txt`:
```
2022-07-17 12:57:27 - [main.c:1834] Parsing CLI Args
2022-07-17 12:57:27 - [main.c:1881] Using ext-session-lock-v1
2022-07-17 12:57:27 - [main.c:688] output name is HDMI-A-1
2022-07-17 12:57:27 - [main.c:344] Surface for output HDMI-A-1 ready
2022-07-17 12:57:27 - [main.c:688] output name is eDP-1
2022-07-17 12:57:27 - [main.c:344] Surface for output eDP-1 ready
ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured
```

**Comment by jirutka** [comment]
That’s weird; I’m using it on Alpine Linux v3.16 with Sway 1.7 and don’t experience this problem.

**Comment by ErikReider** [comment]
> That’s weird; I’m using it on Alpine Linux v3.16 with Sway 1.7 and don’t experience this problem.

Have you tried sway 1.8? (master branch)

**Comment by PeterCxy** [comment]
I just updated to sway-git master today and ran into this problem. Seems like something must have changed within the past 2 - 3 weeks (last time I updated should be less than 1 month ago)

**Comment by simonm** [comment]
To confirm @PeterCxy comments: I just rolled back from -git versions of wlroots and sway and now red screen problems and also issue #5 are resolved for me.

**Comment by oxalica** [comment]
Any update? I'm using the latest master `sway` and `swaylock-effects` of this repo. Still run into this issue, making it totally unusable.

**Comment by frap129** [comment]
@oxalica The only solution I've found is using the release version of sway and wlroots.

**Comment by oxalica** [comment]
> @oxalica The only solution I've found is using the release version of sway and wlroots.

Release version of `sway` has not impl `ext-session-lock` feature and thus hide this issue but not resolve it.

But the reason why I'm seeking for this fork is just because it claims to include the `ext-session-lock` impl https://github.com/jirutka/swaylock-effects/commit/1d1c75b6316d21933069a9d201f966d84099f6ca . Without it (like the previous fork https://github.com/mortie/swaylock-effects), keyboard input can bypass the lock when display is turned off, making the lock effectively useless. This would not be better than the original unmaintained fork to me.

**Comment by jirutka** [comment]
No progress yet. :( I don't where exactly is the problem and since Sway 1.8 has not been released yet, thus it's not in stable Alpine, it doesn't bother me for now. I hope that, meanwhile, someone more skilled in Wayland development will help here. If not, I will try to fix it myself, but since I have tone of others things to do, it's unlikely to happen before a) it's causing problem on my system, or b) someone donate me to fix it.

**Comment by bencollerson** [comment]
I had this same problem of a dark screen, active pointer, and no way to unlock on the current jirutka master branch after I rebuilt my dwl with wlroots 0.16.0. Upstream swaylock and mortie/swaylock-effects do not produce this issue. I also did not have this issue when using wlroots 0.15.1.

**Comment by hypperd** [comment]
Apparently using `--screenshots` option, the problem no longer occurs.

**Comment by PeterCxy** [comment]
Please try out patches from #20, that should fix this issue.
